# screen_monitor_plugin - 配置文件
# 让麦麦视奸你
# 配置版本: 1.0.2

[plugin]

# 插件名称
name = "screen_monitor_plugin"

# 插件版本
version = "1.0.0"

# 配置文件版本
config_version = "1.0.2"

# 是否启用插件
enabled = true

[monitor]

# 监控用户名，用于标识记录
username = "拾风"

# 截图间隔（秒）
interval = 30

# 历史记录保留时间（分钟）
retention_minutes = 5


[vlm]

# VLM API基础URL
base_url = "https://api.siliconflow.cn/v1"

# VLM API密钥
api_key = "sk-cwntqrovqklknwbjgbbnkibderknahhauzlfgephvafjbppg"

# 使用的VLM模型标识符
model = "Qwen/Qwen2.5-VL-32B-Instruct"


[llm]

# LLM API基础URL
base_url = "https://api.siliconflow.cn/v1"

# LLM API密钥
api_key = "sk-cwntqrovqklknwbjgbbnkibderknahhauzlfgephvafjbppg"

# 使用的LLM模型标识符
model = "Tongyi-Zhiwen/QwenLong-L1-32B"


